# Imports

##### Note:  
###### $PyInstaller$ was pip installed for containerization.

In [1]:
import pandas as pd # Data manipulation/access
#pd.set_option('display.max_columns', None)
#pd.set_option('display.max_colwidth', None)
import utils # custom utility functions

#import PySimpleGUI as sg # User interface
from IPython.display import display, HTML # Hyperlink access

# Import Data

In [13]:
# import all data
df = utils.return_clean_data('hsp_data.xlsx')

In [5]:
# import findings and results in 2 separate dfs
findings_df = utils.return_clean_data('hsp_data.xlsx').iloc[:, list(range(0,20))]
results_df = utils.return_clean_data('hsp_data.xlsx').iloc[:, list(range(20,35))]

In [15]:
# data preview
df[:4]

,Diffuse or Multifocal,Symmetric,Frontal vs Posterior Predominance,Telltale Grey Matter Involvement,Cortical Involvement/Subcortical Lesions,U-Fiber/Juxtacortical Involvement,Periventricular Involvement:Forceps Major,Periventricular Involvement:Forceps Minor,Periventricular Involvement:Other,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Rostrum,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Genu,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Body,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Isthmus,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Splenium,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Other,Subcortical Structures:Posterior Fossa Involvement:Cerebellar,Subcortical Structures:Posterior Fossa Involvement:Brainstem,Spinal Cord Involvement:Spinal Cord Atrophy,Spinal Cord Involvement:Abnormal Signal/White Matter Tract,Ventriculomegaly vs Hydrocephalus,Gene,Gene/Locus,Position,Genome Browser,Pure vs Complicated,MOI,Onset,Prevalence,Clinical Synopsis,Articles,Articles with MR Images,OMIM,Oprha link,Periventricular Involvement:Other,Bracket notes
0,D,,,,,,,,,agenesis,agenesis,,,,,,,,,hydrocephalus,SPG1,L1CAM,"X:153,861,516-153,886,173",https://www.ncbi.nlm.nih.gov/gene/3897,Complicated,XLR,NN,"1/300,000 Male",GROWTH\nHeight\n- Short stature (<5-15th perce...,"https://pubmed.ncbi.nlm.nih.gov/8305964/ , 10....",https://doi.org/10.1016/S0387-7604(97)00079-X,# 303350 https://www.omim.org/entry/303350,https://www.orpha.net/consor/cgi-bin/OC_Exp.ph...,,
1,"D, M",asymmetric,posterior,,,,ear of lynx,present,present,present,,,,,,"middle cerebellar peduncles, infratentorial le...",pons,present,,,SPG2,PLP1,"X:103,776,506-103,792,619",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,XLR,C,"<1/1,000,000",HEAD & NECK\nEyes\n- Nystagmus\n- Optic atroph...,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...",https://doi.org/10.1016/j.jns.2017.01.069,# 312920 https://www.omim.org/entry/312920?sea...,https://www.orpha.net/consor/cgi-bin/OC_Exp.ph...,,Multifocal - MS like lesions
2,M,,posterior,,"corona radiata, pre and post central gyrus",,,,present,,,,,,,,,mild,,,SPG3A,ATL1,"14:50,533,082-50,633,068",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Pure,AD,"C, A","1-9 / 1,000,000",GENITOURINARY\nBladder\n- Urinary urgency\n- U...,"10.3389/fneur.2023.1239725 , https://www.ncbi....","https://doi.org/10.1007/s00234-005-1415-3 , ht...",#182600 https://www.omim.org/entry/182600?sear...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,
3,,symmetric,posterior,,,,,,present,present,,,,,,atrophy of cerebellum,,present,,ventriculomegaly,SPG4,SPAST,"2:32,063,556-32,157,637+6:35",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Pure,AD,"I, C, AD, A","0.9/100,00",HEAD & NECK\nEyes\n- Nystagmus (rare)\nGENITOU...,"10.1186/s12883-022-02595-4 , https://doi.org/...",https://doi.org/10.1007/s00234-005-1415-3; 10....,#182601 https://www.omim.org/entry/182601?sear...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,

# Data Cleaning

In [2]:
def return_clean_data(data_file):
    '''
    Input: the data file's name ("hsp_data.xlsx"). 
    Output: ready to use df.
    '''
    
    data = pd.read_excel(data_file)

    # remap findings titles to category-specific titles
    titles_map = {'U-fiber/Juxtacortical involvement':'U-Fiber/Juxtacortical Involvement',
                'Cortical involvement/Subcortical Lesions':'Cortical Involvement/Subcortical Lesions',
                'Telltale grey matter involvement':'Telltale Grey Matter Involvement',
                'Forceps major':"Periventricular Involvement:Forceps Major",
                'Forceps minor':"Periventricular Involvement:Forceps Minor",
                'Other':"Periventricular Involvement:Other",
                'Rostrum':"Subcortical Structures:Corpus Callosum Involvement (Atrophy):Rostrum",
                'Genu':"Subcortical Structures:Corpus Callosum Involvement (Atrophy):Genu",
                'Body':"Subcortical Structures:Corpus Callosum Involvement (Atrophy):Body",
                'Isthmus':"Subcortical Structures:Corpus Callosum Involvement (Atrophy):Isthmus",
                'Splenium':"Subcortical Structures:Corpus Callosum Involvement (Atrophy):Splenium",
                'Other.1':"Subcortical Structures:Corpus Callosum Involvement (Atrophy):Other",
                'Cerebellar ':"Subcortical Structures:Posterior Fossa Involvement:Cerebellar",
                'Brainstem':"Subcortical Structures:Posterior Fossa Involvement:Brainstem",
                'Spinal cord atrophy':"Spinal Cord Involvement:Spinal Cord Atrophy",
                'Abnormal signal/white matter tract':"Spinal Cord Involvement:Abnormal Signal/White Matter Tract",
                'Ventriculomegaly vs hydrocephalus':'Ventriculomegaly vs Hydrocephalus',
                'Other.2':'Other'}
    data = data.rename(columns=titles_map)

    # standarize unique values in each column (MRI findings)
    data['Diffuse or Multifocal'] = data['Diffuse or Multifocal'].replace({'D,M':'D, M'})
    data['Periventricular Involvement:Forceps Major'] = data['Periventricular Involvement:Forceps Major'].replace('x','present')
    data['Periventricular Involvement:Forceps Minor'] = data['Periventricular Involvement:Forceps Minor'].replace('x','present')
    data['Periventricular Involvement:Other'] = data['Periventricular Involvement:Other'].replace('x','present')
    data['Subcortical Structures:Corpus Callosum Involvement (Atrophy):Rostrum'] = data['Subcortical Structures:Corpus Callosum Involvement (Atrophy):Rostrum'].replace('x','present')
    data['Subcortical Structures:Corpus Callosum Involvement (Atrophy):Genu'] = data['Subcortical Structures:Corpus Callosum Involvement (Atrophy):Genu'].replace('x','present')
    data['Subcortical Structures:Corpus Callosum Involvement (Atrophy):Body'] = data['Subcortical Structures:Corpus Callosum Involvement (Atrophy):Body'].replace({'x':'present', 'indenture, x ':'indenture, present '})
    data['Subcortical Structures:Corpus Callosum Involvement (Atrophy):Isthmus'] = data['Subcortical Structures:Corpus Callosum Involvement (Atrophy):Isthmus'].replace('x','present')
    data['Subcortical Structures:Corpus Callosum Involvement (Atrophy):Splenium'] = data['Subcortical Structures:Corpus Callosum Involvement (Atrophy):Splenium'].replace('x','present')
    data['Subcortical Structures:Posterior Fossa Involvement:Cerebellar'] = data['Subcortical Structures:Posterior Fossa Involvement:Cerebellar'].replace('x','present')
    data['Spinal Cord Involvement:Spinal Cord Atrophy'] = data['Spinal Cord Involvement:Spinal Cord Atrophy'].replace('x','present')

    # fix missing values values
    data = data.fillna('')
    
    return data

# Data Categories

### 1- MRI findings (Search values)

In [10]:
# MRI findings categories
findings_categorized = {
 'Diffuse or Multifocal':'Diffuse or Multifocal', # 1-dimensional category
 'Symmetric':'Symmetric',
 'Frontal vs Posterior Predominance':'Frontal vs Posterior Predominance',
 'Telltale Grey Matter Involvement':'Telltale Grey Matter Involvement',
 'Cortical Involvement/Subcortical Lesions':'Cortical Involvement/Subcortical Lesions',
 'U-Fiber/Juxtacortical Involvement':'U-Fiber/Juxtacortical Involvement',
 'Ventriculomegaly vs Hydrocephalus':'Ventriculomegaly vs Hydrocephalus',

 'Spinal Cord Involvement':{'Spinal Cord Atrophy':'Spinal Cord Atrophy', # 2-dimensional category
                            'Abnormal Signal/White Matter Tract':'Abnormal Signal/White Matter Tract'},
 'Periventricular Involvement':{'Forceps Major':'Forceps Major',
                                'Forceps Minor':'Forceps Minor',
                                'Other':'Other'},

 'Subcortical Structures':{'Corpus Callosum Involvement (Atrophy)':{'Rostrum':'Rostrum', # 3-dimensional category
                                                                    'Genu':'Genu',
                                                                    'Body':'Body',
                                                                    'Isthmus':'Isthmus',
                                                                    'Splenium':'Splenium',
                                                                    'Other':'Other'},
                           'Posterior Fossa Involvement':{'Cerebellar':'Cerebellar',
                                                          'Brainstem':'Brainstem'}}
}

{'Diffuse or Multifocal': 'Diffuse or Multifocal',
 'Symmetric': 'Symmetric',
 'Frontal vs Posterior Predominance': 'Frontal vs Posterior Predominance',
 'Telltale Grey Matter Involvement': 'Telltale Grey Matter Involvement',
 'Cortical Involvement/Subcortical Lesions': 'Cortical Involvement/Subcortical Lesions',
 'U-Fiber/Juxtacortical Involvement': 'U-Fiber/Juxtacortical Involvement',
 'Ventriculomegaly vs Hydrocephalus': 'Ventriculomegaly vs Hydrocephalus',
 'Spinal Cord Involvement': {'Spinal Cord Atrophy': 'Spinal Cord Atrophy',
  'Abnormal Signal/White Matter Tract': 'Abnormal Signal/White Matter Tract'},
 'Periventricular Involvement': {'Forceps Major': 'Forceps Major',
  'Forceps Minor': 'Forceps Minor',
  'Other': 'Other'},
 'Subcortical Structures': {'Corpus Callosum Involvement (Atrophy)': {'Rostrum': 'Rostrum',
   'Genu': 'Genu',
   'Body': 'Body',
   'Isthmus': 'Isthmus',
   'Splenium': 'Splenium',
   'Other': 'Other'},
  'Posterior Fossa Involvement': {'Cerebellar': 'Cerebellar',
   'Brainstem': 'Brainstem'}}}

### 2- Features (Results)

In [14]:
# results
indices_res = list(range(20,35))
titles_res = df.iloc[:, indices_res].columns
results = dict(zip(indices_res, titles_res))
results

{20: 'Gene',
 21: 'Gene/Locus',
 22: 'Position',
 23: 'Genome Browser',
 24: 'Pure vs Complicated',
 25: 'MOI',
 26: 'Onset',
 27: 'Prevalence',
 28: 'Clinical Synopsis',
 29: 'Articles',
 30: 'Articles with MR Images',
 31: 'OMIM',
 32: 'Oprha link',
 33: 'Other',
 34: 'Bracket notes'}

# Making a Query

In [6]:
# Example of a query result: Frontal vs Posterior Predominance ==> posterior and Periventricular Involvement:Forceps Major ==> ear of lynx
df.loc[(df['Frontal vs Posterior Predominance']=='posterior')&(df['Periventricular Involvement:Forceps Major']=='ear of lynx')][df.iloc[:, list(range(20,35))].columns]

,Gene,Gene/Locus,Position,Genome Browser,Pure vs Complicated,MOI,Onset,Prevalence,Clinical Synopsis,Articles,Articles with MR Images,OMIM,Oprha link,Periventricular Involvement:Other,Periventricular Involvement:Other,Bracket notes
1,SPG2,PLP1,"X:103,776,506-103,792,619",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,XLR,C,"<1/1,000,000",HEAD & NECK\nEyes\n- Nystagmus\n- Optic atroph...,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...",https://doi.org/10.1016/j.jns.2017.01.069,# 312920 https://www.omim.org/entry/312920?sea...,https://www.orpha.net/consor/cgi-bin/OC_Exp.ph...,present,,Multifocal - MS like lesions
16,SPG48,AP5Z1,"7:4,775,623-4,794,397",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Pure,AR,A,"<1 / 1,000,000",HEAD & NECK\nEyes\n- Retinopathy (adult onset ...,"https://doi.org/10.1186/s40035-019-0157-9 , ht...","https://doi.org/10.1093/brain/awu121, https://...",# 613647 https://omim.org/entry/613647?search=...,https://www.orpha.net/consor/cgi-bin/Disease_S...,present,,

# Search Engine Development

#### Note:  

To check if a category has subcategories, check its $type$.  
If it's a $string$ then it has no subcategories else if it's a $dictionnary$ then it has subcategories.

```
>>> utils.check_multiple_dimensions('Subcortical Structures')
True
```

## Version 1

 - Search logic: AND

In [5]:
def run_version1():
    
    # imports
    import pandas as pd # data manipulation/access
    import utils # custom utility functions
    #pd.set_option('display.max_columns', None)
    #pd.set_option('display.max_colwidth', None)
    #from IPython.display import display, HTML # hyperlink access
    
    
    dimension_1 = ['Diffuse or Multifocal','Symmetric','Frontal vs Posterior Predominance','Telltale Grey Matter Involvement','Cortical Involvement/Subcortical Lesions','U-Fiber/Juxtacortical Involvement', 'Ventriculomegaly vs Hydrocephalus']
    dimension_2 = ['Spinal Cord Involvement','Periventricular Involvement']
    dimension_3 = ['Subcortical Structures']

    # main loop
    # flag may be set to False depending on user input
    flag = True
    while flag:
        
        # data
        # as user adds search contraints, irrelevant rows are dropped
        # the dfs reset with every new search
        findings_df = utils.return_clean_data('hsp_data.xlsx').iloc[:, list(range(0,20))]
        results_df = utils.return_clean_data('hsp_data.xlsx').iloc[:, list(range(20,35))]
        df = utils.return_clean_data('hsp_data.xlsx')        
        
        # initially, additional_category is set to True to start a search
        # if set to False, return results with the only selected search category
        additional_category_flag = True
        while additional_category_flag:
            
            # display list of main categories
            access_categories = list(utils.findings_categorized.keys())
            print("List of categories:")
            print("*******************\n")
            print('\n\n'.join(access_categories))
            print()
            print()

            # user input for main category
            category = input("Enter name of MRI finding: ")
            print()
            print("- You chose: [", category,"].")
            print()
            print()
            # check if main category is more than 1 dimension
            if category not in dimension_1:

                # 3 dimension
                if category not in dimension_2:

                    # display list of subcategories
                    access_subcategories = utils.findings_categorized['Subcortical Structures']
                    print("List of subcategories:")
                    print("**********************\n")
                    print('\n\n'.join(list(access_subcategories)))
                    print()
                    print()

                    # user input for subcategory
                    subcategory = input("Choose a subcategory: ")
                    print()
                    print("- You chose: [", subcategory,"].")
                    print()
                    print()

                    # display list of sub-subcategories
                    access_sub_subcategories = access_subcategories[subcategory]
                    print("List of sub_subcategories:")
                    print("**************************\n")
                    print('\n\n'.join(list(access_sub_subcategories)))
                    print()
                    print()

                    # user input for sub_subcategory
                    sub_subcategory = input("Choose a sub_subcategory: ")
                    print()
                    print("- You chose: [", sub_subcategory,"].")

                    # column title
                    col_title = str(category+':'+subcategory+':'+sub_subcategory)

                # 2 dimension
                else:

                    # display list of subcategories
                    access_subcategories = utils.findings_categorized[category]
                    print("\n\nList of subcategories:")
                    print("**********************\n")
                    print('\n\n'.join(list(access_subcategories)))
                    print()
                    print()

                    # user input for subcategory
                    subcategory = input("Choose a subcategory: ")
                    print()
                    print("- You chose: [", subcategory,"].")
                    print()
                    print()

                    # column title
                    col_title = str(category+':'+subcategory)

            # 1 dimension        
            else:

                # column title
                col_title = category

            print()
            print()

            # display list of values of interest
            access_values_of_interest = findings_df[col_title].unique().tolist()
            print("List of Values of Interest:")
            print("***************************\n")
            access_values_of_interest.remove('') if ('' in access_values_of_interest) else None
            print('\n\n'.join(access_values_of_interest))
            print()

            # user input for value of interest
            value_of_interest = input("Choose a value of interest: ")
            print()
            print("- You chose: [", value_of_interest,"].")

            # keep relevant rows
            findings_df = findings_df.loc[(findings_df[col_title]==value_of_interest)]

            # prompt user to add additional search constraint
            add_a_category = input("\n\nWould you to add another category? ")
            if add_a_category == '0' or add_a_category.lower()=="no":
                additional_category_flag = False
        print()
        print()

        # return results
        display(df.loc[findings_df.index])

        # terminate/new search
        terminate = input("Would you like to search again? ")
        if terminate == '0' or terminate.lower() == 'no':
            flag = False

    # exit message
    print("Goodbye!")

### Testing Version 1

#### - Testing normal output
* 1st category
- Spinal Cord Involvement
- Spinal Cord Atrophy
- present
* 2nd category
- Frontal vs Posterior Predominance
- posterior

In [2]:
run_version1()

List of categories:
*******************

Diffuse or Multifocal

Symmetric

Frontal vs Posterior Predominance

Telltale Grey Matter Involvement

Cortical Involvement/Subcortical Lesions

U-Fiber/Juxtacortical Involvement

Ventriculomegaly vs Hydrocephalus

Spinal Cord Involvement

Periventricular Involvement

Subcortical Structures

Enter name of MRI finding:  Spinal Cord Involvement

- You chose: [ Spinal Cord Involvement ].




List of subcategories:
**********************

Spinal Cord Atrophy

Abnormal Signal/White Matter Tract

Choose a subcategory:  Spinal Cord Atrophy

- You chose: [ Spinal Cord Atrophy ].




List of Values of Interest:
***************************

present

mild

rare

Choose a value of interest:  present

- You chose: [ present ].

Would you to add another category?  yes

List of categories:
*******************

Diffuse or Multifocal

Symmetric

Frontal vs Posterior Predominance

Telltale Grey Matter Involvement

Cortical Involvement/Subcortical Lesions

U-Fiber/Juxtacortical Involvement

Ventriculomegaly vs Hydrocephalus

Spinal Cord Involvement

Periventricular Involvement

Subcortical Structures

Enter name of MRI finding:  Frontal vs Posterior Predominance

- You chose: [ Frontal vs Posterior Predominance ].




List of Values of Interest:
***************************

posterior

frontal

Choose a value of interest:  posterior

- You chose: [ posterior ].

Would you to add another category?  no

,Diffuse or Multifocal,Symmetric,Frontal vs Posterior Predominance,Telltale Grey Matter Involvement,Cortical Involvement/Subcortical Lesions,U-Fiber/Juxtacortical Involvement,Periventricular Involvement:Forceps Major,Periventricular Involvement:Forceps Minor,Periventricular Involvement:Other,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Rostrum,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Genu,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Body,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Isthmus,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Splenium,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Other,Subcortical Structures:Posterior Fossa Involvement:Cerebellar,Subcortical Structures:Posterior Fossa Involvement:Brainstem,Spinal Cord Involvement:Spinal Cord Atrophy,Spinal Cord Involvement:Abnormal Signal/White Matter Tract,Ventriculomegaly vs Hydrocephalus,Gene,Gene/Locus,Position,Genome Browser,Pure vs Complicated,MOI,Onset,Prevalence,Clinical Synopsis,Articles,Articles with MR Images,OMIM,Oprha link,Periventricular Involvement:Other,Bracket notes
1,"D, M",asymmetric,posterior,,,,ear of lynx,present,present,present,,,,,,"middle cerebellar peduncles, infratentorial le...",pons,present,,,SPG2,PLP1,"X:103,776,506-103,792,619",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,XLR,C,"<1/1,000,000",HEAD & NECK\nEyes\n- Nystagmus\n- Optic atroph...,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...",https://doi.org/10.1016/j.jns.2017.01.069,# 312920 https://www.omim.org/entry/312920?sea...,https://www.orpha.net/consor/cgi-bin/OC_Exp.ph...,,Multifocal - MS like lesions
3,,symmetric,posterior,,,,,,present,present,,,,,,atrophy of cerebellum,,present,,ventriculomegaly,SPG4,SPAST,"2:32,063,556-32,157,637+6:35",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Pure,AD,"I, C, AD, A","0.9/100,00",HEAD & NECK\nEyes\n- Nystagmus (rare)\nGENITOU...,"10.1186/s12883-022-02595-4 , https://doi.org/...",https://doi.org/10.1007/s00234-005-1415-3; 10....,#182601 https://www.omim.org/entry/182601?sear...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,
14,D,,posterior,,,,,,present,,,present,present,,,atrophy of vermis,,present,,ventriculomegaly,SPG46,GBA2,"9:35,736,866-35,749,228",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,AR,"I, C","<1 / 1,000,000",HEAD & NECK\nEars\n- Hearing loss (in some pat...,"10.3389/fneur.2018.01117 , 10.1016/j.ajhg.2012...","https://doi.org/10.1007/s10048-010-0249-2 , 10...",# 614409 https://www.omim.org/entry/614409?sea...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,

Would you like to search again?  no

Goodbye!

#### - Testing normal output
* 1st category
- Ventriculomegaly vs Hydrocephalus
- ventriculomegaly

* 2nd category
- Symmetric
- symmetric

* 3rd category
- Periventricular Involvement
- Forceps Major
- present

In [2]:
run_version1()

List of categories:
*******************

Diffuse or Multifocal

Symmetric

Frontal vs Posterior Predominance

Telltale Grey Matter Involvement

Cortical Involvement/Subcortical Lesions

U-Fiber/Juxtacortical Involvement

Ventriculomegaly vs Hydrocephalus

Spinal Cord Involvement

Periventricular Involvement

Subcortical Structures

Enter name of MRI finding:  Ventriculomegaly vs Hydrocephalus

- You chose: [ Ventriculomegaly vs Hydrocephalus ].




List of Values of Interest:
***************************

hydrocephalus

ventriculomegaly

asymmetric ventriculomegaly + CSF issue

Choose a value of interest:  ventriculomegaly

- You chose: [ ventriculomegaly ].

Would you to add another category?  yes

List of categories:
*******************

Diffuse or Multifocal

Symmetric

Frontal vs Posterior Predominance

Telltale Grey Matter Involvement

Cortical Involvement/Subcortical Lesions

U-Fiber/Juxtacortical Involvement

Ventriculomegaly vs Hydrocephalus

Spinal Cord Involvement

Periventricular Involvement

Subcortical Structures

Enter name of MRI finding:  Symmetric

- You chose: [ Symmetric ].




List of Values of Interest:
***************************

symmetric

symmetric and asymmetric

Choose a value of interest:  symmetric

- You chose: [ symmetric ].

Would you to add another category?  yes

List of categories:
*******************

Diffuse or Multifocal

Symmetric

Frontal vs Posterior Predominance

Telltale Grey Matter Involvement

Cortical Involvement/Subcortical Lesions

U-Fiber/Juxtacortical Involvement

Ventriculomegaly vs Hydrocephalus

Spinal Cord Involvement

Periventricular Involvement

Subcortical Structures

Enter name of MRI finding:  Periventricular Involvement

- You chose: [ Periventricular Involvement ].




List of subcategories:
**********************

Forceps Major

Forceps Minor

Other

Choose a subcategory:  Forceps Major

- You chose: [ Forceps Major ].




List of Values of Interest:
***************************

present

ear of lynx

Choose a value of interest:  present

- You chose: [ present ].

Would you to add another category?  no

,Diffuse or Multifocal,Symmetric,Frontal vs Posterior Predominance,Telltale Grey Matter Involvement,Cortical Involvement/Subcortical Lesions,U-Fiber/Juxtacortical Involvement,Periventricular Involvement:Forceps Major,Periventricular Involvement:Forceps Minor,Periventricular Involvement:Other,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Rostrum,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Genu,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Body,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Isthmus,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Splenium,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Other,Subcortical Structures:Posterior Fossa Involvement:Cerebellar,Subcortical Structures:Posterior Fossa Involvement:Brainstem,Spinal Cord Involvement:Spinal Cord Atrophy,Spinal Cord Involvement:Abnormal Signal/White Matter Tract,Ventriculomegaly vs Hydrocephalus,Gene,Gene/Locus,Position,Genome Browser,Pure vs Complicated,MOI,Onset,Prevalence,Clinical Synopsis,Articles,Articles with MR Images,OMIM,Oprha link,Periventricular Involvement:Other,Bracket notes
7,D,symmetric,posterior,,,,present,present,present,,,,,present,,mild atrophy of vermis,,,,ventriculomegaly,SPG9B,ALDH18A1,"10:95,605,941-95,656,711",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,AR,"I, AD, A","<1 / 1,000,000",GROWTH\nHeight\n- Short stature\nOther\n- Grow...,"10.7860/JCDR/2021/49813.15390 , 10.3389/fneur....",https://doi.org/10.1016/j.braindev.2020.07.015,# 616586 https://www.omim.org/entry/616586?sea...,https://www.orpha.net/consor/cgi-bin/Disease_S...,Not many articles w/ MRI's. Patient is 2.5 yea...,
19,"D, M",symmetric,,,"global white matter atrophy, BPP",hypomyelination,present,,,,,,,,thin CC,,,,,ventriculomegaly,SPG52,AP4S1,"14:31,025,106-31,096,450",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,AR,"I, NN","<1 / 1,000,000",GROWTH\nHeight\n- Short stature\nHEAD & NECK\n...,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...","10.1093/brain/awz307 , 10.1212/WNL.00000000000...",# 614067 https://www.omim.org/entry/614067?sea...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,

Would you like to search again?  no

Goodbye!

## Version 2
* Search logic: OR - Added filtering feature to select all rows with chosen value of interest present regardless of presence of additonal values.
* Keyboard interrupt feature (press enter)

In [19]:
def run_version2():
    
    # imports
    import pandas as pd # data manipulation/access
    import utils # custom utility functions
    #pd.set_option('display.max_columns', None)
    #pd.set_option('display.max_colwidth', None)
    #from IPython.display import display, HTML # hyperlink access

    dimension_1 = ['Diffuse or Multifocal','Symmetric','Frontal vs Posterior Predominance','Telltale Grey Matter Involvement','Cortical Involvement/Subcortical Lesions','U-Fiber/Juxtacortical Involvement', 'Ventriculomegaly vs Hydrocephalus']
    dimension_2 = ['Spinal Cord Involvement','Periventricular Involvement']
    dimension_3 = ['Subcortical Structures']

    # main loop
    # flag may be set to False depending on user input
    flag = True
    while flag:

        # data
        # as user adds search contraints, irrelevant rows are dropped
        # the dfs reset with every new search
        findings_df = utils.return_clean_data('hsp_data.xlsx').iloc[:, list(range(0,20))]
        results_df = utils.return_clean_data('hsp_data.xlsx').iloc[:, list(range(20,35))]
        df = utils.return_clean_data('hsp_data.xlsx')        

        # initially, additional_category is set to True to start a search
        # if set to False, return results with the only selected search category
        additional_category_flag = True
        while additional_category_flag:

            # display list of main categories
            access_categories = list(utils.findings_categorized.keys())
            print("List of categories:")
            print("*******************\n")
            print('\n\n'.join(access_categories))
            print()
            print()

            # user input for main category #
            category = input("Enter name of MRI finding: ")
            
            # keyboard interrupt
            if category == "":
                return "Forced exit. Goodbye!"
            
            # invalid input handling #
            while category not in access_categories:
                print()
                category = input("Invalid input. Choose a category from the list above (case sensitive): ")
            
            print()
            print("- You chose: [", category,"].")
            print()
            print()
            
            # check if main category is more than 1 dimension
            if category not in dimension_1:

                # 3 dimension
                if category not in dimension_2:

                    # display list of subcategories
                    access_subcategories = utils.findings_categorized['Subcortical Structures']
                    print("List of subcategories:")
                    print("**********************\n")
                    print('\n\n'.join(list(access_subcategories)))
                    print()
                    print()

                    # user input for subcategory #
                    subcategory = input("Choose a subcategory: ")

                    # keyboard interrupt
                    if subcategory == "":
                        return "Forced exit. Goodbye!"
                    
                    # invalid input handling #
                    while subcategory not in access_subcategories:
                        print()
                        subcategory = input("Invalid input. Choose a subcategory from the list above (case sensitive): ")

                    print()
                    print("- You chose: [", subcategory,"].")
                    print()
                    print()

                    # display list of sub-subcategories
                    access_sub_subcategories = access_subcategories[subcategory]
                    print("List of sub_subcategories:")
                    print("**************************\n")
                    print('\n\n'.join(list(access_sub_subcategories)))
                    print()
                    print()

                    # user input for sub_subcategory #
                    sub_subcategory = input("Choose a sub_subcategory: ")

                    # keyboard interrupt
                    if sub_subcategory == "":
                        return "Forced exit. Goodbye!"
                    
                    # invalid input handling #
                    while sub_subcategory not in access_sub_subcategories:
                        print()
                        sub_subcategory = input("Invalid input. Choose a subcategory from the list above (case sensitive): ")
                        
                    print()
                    print("- You chose: [", sub_subcategory,"].")

                    # column title
                    col_title = str(category+':'+subcategory+':'+sub_subcategory)

                # 2 dimension
                else:

                    # display list of subcategories
                    access_subcategories = utils.findings_categorized[category]
                    print("\n\nList of subcategories:")
                    print("**********************\n")
                    print('\n\n'.join(list(access_subcategories)))
                    print()
                    print()

                    # user input for subcategory #
                    subcategory = input("Choose a subcategory: ")

                    # keyboard interrupt
                    if subcategory == "":
                        return "Forced exit. Goodbye!"
                    
                    # invalid input handling #
                    while subcategory not in access_subcategories:
                        print()
                        subcategory = input("Invalid input. Choose a subcategory from the list above (case sensitive): ")

                    print()
                    print("- You chose: [", subcategory,"].")
                    print()
                    print()

                    # column title
                    col_title = str(category+':'+subcategory)

            # 1 dimension        
            else:

                # column title
                col_title = category

            print()
            print()

            # display list of values of interest
            access_values_of_interest = findings_df[col_title].unique().tolist()
            print("List of Values of Interest:")
            print("***************************\n")
            access_values_of_interest.remove('') if ('' in access_values_of_interest) else None
            print('\n\n'.join(access_values_of_interest))
            print()

            # user input for value of interest #
            value_of_interest = input("Choose a value of interest: ")

            # keyboard interrupt
            if value_of_interest == "":
                return "Forced exit. Goodbye!"
            
            # invalid input handling #
            while value_of_interest not in access_values_of_interest:
                print()
                value_of_interest = input("Invalid input. Choose a value of interest from the list above (case sensitive): ")

            print()
            print("- You chose: [", value_of_interest,"].")

            # keep relevant rows
            findings_df = findings_df.loc[(findings_df[col_title].str.contains(value_of_interest, case=False, na=False))]

            # prompt user to add additional search constraint #
            add_a_category = input("\n\nWould you to add another category? ")

            # keyboard interrupt
            if add_a_category == "":
                return "Forced exit. Goodbye!"

            if add_a_category == '0' or add_a_category.lower()=="no":
                additional_category_flag = False
        print()
        print()

        # return results
        display(df.loc[findings_df.index])

        # prompt user to start new search #
        terminate = input("Would you like to search again? ")

        # keyboard interrupt
        if terminate == "":
            return "Forced exit. Goodbye!"

        if terminate == '0' or terminate.lower() == 'no':
            flag = False

    # exit message
    print("Goodbye!")

### Testing Version 2

#### - Testing keyboard interrupt feature

In [20]:
run_version2()

List of categories:
*******************

Diffuse or Multifocal

Symmetric

Frontal vs Posterior Predominance

Telltale Grey Matter Involvement

Cortical Involvement/Subcortical Lesions

U-Fiber/Juxtacortical Involvement

Ventriculomegaly vs Hydrocephalus

Spinal Cord Involvement

Periventricular Involvement

Subcortical Structures

Enter name of MRI finding:

'Forced exit. Goodbye!'

#### - Testing invalid input handling (all levels)

In [21]:
run_version2()

List of categories:
*******************

Diffuse or Multifocal

Symmetric

Frontal vs Posterior Predominance

Telltale Grey Matter Involvement

Cortical Involvement/Subcortical Lesions

U-Fiber/Juxtacortical Involvement

Ventriculomegaly vs Hydrocephalus

Spinal Cord Involvement

Periventricular Involvement

Subcortical Structures

Enter name of MRI finding:  goose

Invalid input. Choose a category from the list above (case sensitive):  wii

Invalid input. Choose a category from the list above (case sensitive):  Subcortical Structures

- You chose: [ Subcortical Structures ].


List of subcategories:
**********************

Corpus Callosum Involvement (Atrophy)

Posterior Fossa Involvement

Choose a subcategory:  yes

Invalid input. Choose a subcategory from the list above (case sensitive):  Posterior Fossa Involvement

- You chose: [ Posterior Fossa Involvement ].


List of sub_subcategories:
**************************

Cerebellar

Brainstem

Choose a sub_subcategory:  yes

Invalid input. Choose a subcategory from the list above (case sensitive):  Brainstem

- You chose: [ Brainstem ].


List of Values of Interest:
***************************

pons

Choose a value of interest:  l

Invalid input. Choose a value of interest from the list above (case sensitive):  pons

- You chose: [ pons ].

Would you to add another category?  no

,Diffuse or Multifocal,Symmetric,Frontal vs Posterior Predominance,Telltale Grey Matter Involvement,Cortical Involvement/Subcortical Lesions,U-Fiber/Juxtacortical Involvement,Periventricular Involvement:Forceps Major,Periventricular Involvement:Forceps Minor,Periventricular Involvement:Other,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Rostrum,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Genu,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Body,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Isthmus,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Splenium,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Other,Subcortical Structures:Posterior Fossa Involvement:Cerebellar,Subcortical Structures:Posterior Fossa Involvement:Brainstem,Spinal Cord Involvement:Spinal Cord Atrophy,Spinal Cord Involvement:Abnormal Signal/White Matter Tract,Ventriculomegaly vs Hydrocephalus,Gene,Gene/Locus,Position,Genome Browser,Pure vs Complicated,MOI,Onset,Prevalence,Clinical Synopsis,Articles,Articles with MR Images,OMIM,Oprha link,Periventricular Involvement:Other,Bracket notes
1,"D, M",asymmetric,posterior,,,,ear of lynx,present,present,present,,,,,,"middle cerebellar peduncles, infratentorial le...",pons,present,,,SPG2,PLP1,"X:103,776,506-103,792,619",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,XLR,C,"<1/1,000,000",HEAD & NECK\nEyes\n- Nystagmus\n- Optic atroph...,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...",https://doi.org/10.1016/j.jns.2017.01.069,# 312920 https://www.omim.org/entry/312920?sea...,https://www.orpha.net/consor/cgi-bin/OC_Exp.ph...,,Multifocal - MS like lesions

Would you like to search again?  no

Goodbye!

#### - Testing normal output version 1 vs version 2
- U-Fiber/Juxtacortical Involvement
- hypomyelination

In [6]:
# version 1
run_version1()

List of categories:
*******************

Diffuse or Multifocal

Symmetric

Frontal vs Posterior Predominance

Telltale Grey Matter Involvement

Cortical Involvement/Subcortical Lesions

U-Fiber/Juxtacortical Involvement

Ventriculomegaly vs Hydrocephalus

Spinal Cord Involvement

Periventricular Involvement

Subcortical Structures

Enter name of MRI finding:  U-Fiber/Juxtacortical Involvement

- You chose: [ U-Fiber/Juxtacortical Involvement ].




List of Values of Interest:
***************************

hypomyelination

Choose a value of interest:  hypomyelination

- You chose: [ hypomyelination ].

Would you to add another category?  no

,Diffuse or Multifocal,Symmetric,Frontal vs Posterior Predominance,Telltale Grey Matter Involvement,Cortical Involvement/Subcortical Lesions,U-Fiber/Juxtacortical Involvement,Periventricular Involvement:Forceps Major,Periventricular Involvement:Forceps Minor,Periventricular Involvement:Other,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Rostrum,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Genu,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Body,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Isthmus,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Splenium,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Other,Subcortical Structures:Posterior Fossa Involvement:Cerebellar,Subcortical Structures:Posterior Fossa Involvement:Brainstem,Spinal Cord Involvement:Spinal Cord Atrophy,Spinal Cord Involvement:Abnormal Signal/White Matter Tract,Ventriculomegaly vs Hydrocephalus,Gene,Gene/Locus,Position,Genome Browser,Pure vs Complicated,MOI,Onset,Prevalence,Clinical Synopsis,Articles,Articles with MR Images,OMIM,Oprha link,Periventricular Involvement:Other,Bracket notes
19,"D, M",symmetric,,,"global white matter atrophy, BPP",hypomyelination,present,,,,,,,,thin CC,,,,,ventriculomegaly,SPG52,AP4S1,"14:31,025,106-31,096,450",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,AR,"I, NN","<1 / 1,000,000",GROWTH\nHeight\n- Short stature\nHEAD & NECK\n...,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...","10.1093/brain/awz307 , 10.1212/WNL.00000000000...",# 614067 https://www.omim.org/entry/614067?sea...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,

Would you like to search again?  no

Goodbye!

In [4]:
# version 2
run_version2()

List of categories:
*******************

Diffuse or Multifocal

Symmetric

Frontal vs Posterior Predominance

Telltale Grey Matter Involvement

Cortical Involvement/Subcortical Lesions

U-Fiber/Juxtacortical Involvement

Ventriculomegaly vs Hydrocephalus

Spinal Cord Involvement

Periventricular Involvement

Subcortical Structures

Enter name of MRI finding:  U-Fiber/Juxtacortical Involvement

- You chose: [ U-Fiber/Juxtacortical Involvement ].




List of Values of Interest:
***************************

hypomyelination

Choose a value of interest:  hypomyelination

- You chose: [ hypomyelination ].

Would you to add another category?  no

,Diffuse or Multifocal,Symmetric,Frontal vs Posterior Predominance,Telltale Grey Matter Involvement,Cortical Involvement/Subcortical Lesions,U-Fiber/Juxtacortical Involvement,Periventricular Involvement:Forceps Major,Periventricular Involvement:Forceps Minor,Periventricular Involvement:Other,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Rostrum,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Genu,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Body,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Isthmus,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Splenium,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Other,Subcortical Structures:Posterior Fossa Involvement:Cerebellar,Subcortical Structures:Posterior Fossa Involvement:Brainstem,Spinal Cord Involvement:Spinal Cord Atrophy,Spinal Cord Involvement:Abnormal Signal/White Matter Tract,Ventriculomegaly vs Hydrocephalus,Gene,Gene/Locus,Position,Genome Browser,Pure vs Complicated,MOI,Onset,Prevalence,Clinical Synopsis,Articles,Articles with MR Images,OMIM,Oprha link,Periventricular Involvement:Other,Bracket notes
19,"D, M",symmetric,,,"global white matter atrophy, BPP",hypomyelination,present,,,,,,,,thin CC,,,,,ventriculomegaly,SPG52,AP4S1,"14:31,025,106-31,096,450",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,AR,"I, NN","<1 / 1,000,000",GROWTH\nHeight\n- Short stature\nHEAD & NECK\n...,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...","10.1093/brain/awz307 , 10.1212/WNL.00000000000...",# 614067 https://www.omim.org/entry/614067?sea...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,

Would you like to search again?  no

Goodbye!

####  - Testing OR search logic for values of interests version 1 vs version 2 (ex. "ear of lynx" and "ear of lynx, ears of grizzly")
* Periventricular Involvement
* Forceps Major
* ear of lynx

In [15]:
# version 1
run_version1()

List of categories:
*******************

Diffuse or Multifocal

Symmetric

Frontal vs Posterior Predominance

Telltale Grey Matter Involvement

Cortical Involvement/Subcortical Lesions

U-Fiber/Juxtacortical Involvement

Ventriculomegaly vs Hydrocephalus

Spinal Cord Involvement

Periventricular Involvement

Subcortical Structures

Enter name of MRI finding:  Periventricular Involvement

- You chose: [ Periventricular Involvement ].




List of subcategories:
**********************

Forceps Major

Forceps Minor

Other

Choose a subcategory:  Forceps Major

- You chose: [ Forceps Major ].




List of Values of Interest:
***************************

ear of lynx

present

ear of lynx, ears of grizzly

Choose a value of interest:  ear of lynx

- You chose: [ ear of lynx ].

Would you to add another category?  no

,Diffuse or Multifocal,Symmetric,Frontal vs Posterior Predominance,Telltale Grey Matter Involvement,Cortical Involvement/Subcortical Lesions,U-Fiber/Juxtacortical Involvement,Periventricular Involvement:Forceps Major,Periventricular Involvement:Forceps Minor,Periventricular Involvement:Other,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Rostrum,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Genu,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Body,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Isthmus,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Splenium,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Other,Subcortical Structures:Posterior Fossa Involvement:Cerebellar,Subcortical Structures:Posterior Fossa Involvement:Brainstem,Spinal Cord Involvement:Spinal Cord Atrophy,Spinal Cord Involvement:Abnormal Signal/White Matter Tract,Ventriculomegaly vs Hydrocephalus,Gene,Gene/Locus,Position,Genome Browser,Pure vs Complicated,MOI,Onset,Prevalence,Clinical Synopsis,Articles,Articles with MR Images,OMIM,Oprha link,Periventricular Involvement:Other,Bracket notes
1,"D, M",asymmetric,posterior,,,,ear of lynx,present,present,present,,,,,,"middle cerebellar peduncles, infratentorial le...",pons,present,,,SPG2,PLP1,"X:103,776,506-103,792,619",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,XLR,C,"<1/1,000,000",HEAD & NECK\nEyes\n- Nystagmus\n- Optic atroph...,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...",https://doi.org/10.1016/j.jns.2017.01.069,# 312920 https://www.omim.org/entry/312920?sea...,https://www.orpha.net/consor/cgi-bin/OC_Exp.ph...,,Multifocal - MS like lesions
4,"D, M",symmetric,frontal,,"corona radiata, centrum smiovale",,ear of lynx,present,present,,present,,present,,,middle cerebellar peduncles,,present,,,SPG5A,CYP7B1,"8:64,586,575-64,798,737",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Both,AR,"C, AD","<1 / 1,000,000",HEAD & NECK:\nEars\n- Sensorineural hearing lo...,"https://doi.org/10.3174/ajnr.A7344 , 10.3389/f...","https://doi.org/10.1016/j.nmd.2008.10.009 , 10...",#270800 https://www.omim.org/entry/270800?sear...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,
8,D,symmetric,frontal,,cortical atrophy,,ear of lynx,present,,present,present,present,present,,,mild atrophy of vermis,,,,ventriculomegaly,SPG11,,"15:44,562,696-44,663,662",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,AR,"I, C, AD, A","0.35/100,000",GROWTH\nWeight\n- Obesity\nHEAD & NECK\nEyes\n...,"https://doi.org/10.1002/mds.28519 , https://d...","10.3389/fneur.2018.01117 , https://doi.org/10....",# 604360 https://www.omim.org/entry/604360?sea...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,
9,D,symmetric,frontal,,,,ear of lynx,present,,,present,present,present,,,mild atrophy of vermis,,rare,,,SPG15,ZFYVE26,"14:67,728,892-67,816,590",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,AR,"C, AD, A","<1 / 1,000,000",HEAD & NECK\nEars\n- Hearing deficit\nEyes\n- ...,"https://doi.org/10.1016/j.ajhg.2008.03.004 , h...","10.3389/fneur.2018.01117 , https://doi.org/10....",# 270700 https://www.omim.org/entry/270700?sea...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,
16,"D, M",symmetric,posterior,,subcortical lesions,,ear of lynx,present,present,,present,present,indenture,,,mild atrophy of cerebellum,,,,,SPG48,AP5Z1,"7:4,775,623-4,794,397",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Pure,AR,A,"<1 / 1,000,000",HEAD & NECK\nEyes\n- Retinopathy (adult onset ...,"https://doi.org/10.1186/s40035-019-0157-9 , ht...","https://doi.org/10.1093/brain/awu121, https://...",# 613647 https://omim.org/entry/613647?search=...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,
17,D,symmetric,,globus pallida calcifications,,,ear of lynx,present,,,,present,,,,,,,,,SPG49,TECPR2,,,Complicated,AR,I,"<1 / 1,000,000",,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...",https://doi.org/10.1016/j.ajhg.2012.11.001,,https://www.orpha.net/consor/cgi-bin/Disease_S...,Now called HSAN9,
20,D,symmetric,,,probable microcephaly,,ear of lynx,present,present,,,"indenture, present",present,present,thinning post genu,,,,,,SPG54,DDHD2,"8:38,231,585-38,273,647",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,AR,"I, C","<1 / 1,000,000",GROWTH\nHeight\n- Short stature\nHEAD & NECK\n...,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...",https://doi-org.proxy3.library.mcgill.ca/10.11...,# 615033 https://www.omim.org/entry/615033?sea...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,

Would you like to search again?  no

Goodbye!

In [12]:
# version 2
run_version2()

List of categories:
*******************

Diffuse or Multifocal

Symmetric

Frontal vs Posterior Predominance

Telltale Grey Matter Involvement

Cortical Involvement/Subcortical Lesions

U-Fiber/Juxtacortical Involvement

Ventriculomegaly vs Hydrocephalus

Spinal Cord Involvement

Periventricular Involvement

Subcortical Structures

Enter name of MRI finding:  Periventricular Involvement

- You chose: [ Periventricular Involvement ].




List of subcategories:
**********************

Forceps Major

Forceps Minor

Other

Choose a subcategory:  Forceps Major

- You chose: [ Forceps Major ].




List of Values of Interest:
***************************

ear of lynx

present

ear of lynx, ears of grizzly

Choose a value of interest:  ear of lynx

- You chose: [ ear of lynx ].

Would you to add another category?  no

,Diffuse or Multifocal,Symmetric,Frontal vs Posterior Predominance,Telltale Grey Matter Involvement,Cortical Involvement/Subcortical Lesions,U-Fiber/Juxtacortical Involvement,Periventricular Involvement:Forceps Major,Periventricular Involvement:Forceps Minor,Periventricular Involvement:Other,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Rostrum,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Genu,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Body,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Isthmus,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Splenium,Subcortical Structures:Corpus Callosum Involvement (Atrophy):Other,Subcortical Structures:Posterior Fossa Involvement:Cerebellar,Subcortical Structures:Posterior Fossa Involvement:Brainstem,Spinal Cord Involvement:Spinal Cord Atrophy,Spinal Cord Involvement:Abnormal Signal/White Matter Tract,Ventriculomegaly vs Hydrocephalus,Gene,Gene/Locus,Position,Genome Browser,Pure vs Complicated,MOI,Onset,Prevalence,Clinical Synopsis,Articles,Articles with MR Images,OMIM,Oprha link,Periventricular Involvement:Other,Bracket notes
1,"D, M",asymmetric,posterior,,,,ear of lynx,present,present,present,,,,,,"middle cerebellar peduncles, infratentorial le...",pons,present,,,SPG2,PLP1,"X:103,776,506-103,792,619",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,XLR,C,"<1/1,000,000",HEAD & NECK\nEyes\n- Nystagmus\n- Optic atroph...,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...",https://doi.org/10.1016/j.jns.2017.01.069,# 312920 https://www.omim.org/entry/312920?sea...,https://www.orpha.net/consor/cgi-bin/OC_Exp.ph...,,Multifocal - MS like lesions
4,"D, M",symmetric,frontal,,"corona radiata, centrum smiovale",,ear of lynx,present,present,,present,,present,,,middle cerebellar peduncles,,present,,,SPG5A,CYP7B1,"8:64,586,575-64,798,737",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Both,AR,"C, AD","<1 / 1,000,000",HEAD & NECK:\nEars\n- Sensorineural hearing lo...,"https://doi.org/10.3174/ajnr.A7344 , 10.3389/f...","https://doi.org/10.1016/j.nmd.2008.10.009 , 10...",#270800 https://www.omim.org/entry/270800?sear...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,
8,D,symmetric,frontal,,cortical atrophy,,ear of lynx,present,,present,present,present,present,,,mild atrophy of vermis,,,,ventriculomegaly,SPG11,,"15:44,562,696-44,663,662",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,AR,"I, C, AD, A","0.35/100,000",GROWTH\nWeight\n- Obesity\nHEAD & NECK\nEyes\n...,"https://doi.org/10.1002/mds.28519 , https://d...","10.3389/fneur.2018.01117 , https://doi.org/10....",# 604360 https://www.omim.org/entry/604360?sea...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,
9,D,symmetric,frontal,,,,ear of lynx,present,,,present,present,present,,,mild atrophy of vermis,,rare,,,SPG15,ZFYVE26,"14:67,728,892-67,816,590",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,AR,"C, AD, A","<1 / 1,000,000",HEAD & NECK\nEars\n- Hearing deficit\nEyes\n- ...,"https://doi.org/10.1016/j.ajhg.2008.03.004 , h...","10.3389/fneur.2018.01117 , https://doi.org/10....",# 270700 https://www.omim.org/entry/270700?sea...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,
15,D,symmetric and asymmetric,posterior,,"cortical malformation, BPP",,"ear of lynx, ears of grizzly",ears of grizzly,heterotopia,,,present,severe atrophy,severe atrophy,"short CC, hemigenesis",mild atrophy of vermis,,,,ventriculomegaly,SPG47,AP4B1,"1:113,894,194-113,905,028",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,AR,"I, NN","<1 / 1,000,000",GROWTH\nHeight\n- Short stature\nHEAD & NECK\n...,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...","10.1093/brain/awz307 , https://doi.org/10.1002...",# 614066 https://www.omim.org/entry/614066?sea...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,
16,"D, M",symmetric,posterior,,subcortical lesions,,ear of lynx,present,present,,present,present,indenture,,,mild atrophy of cerebellum,,,,,SPG48,AP5Z1,"7:4,775,623-4,794,397",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Pure,AR,A,"<1 / 1,000,000",HEAD & NECK\nEyes\n- Retinopathy (adult onset ...,"https://doi.org/10.1186/s40035-019-0157-9 , ht...","https://doi.org/10.1093/brain/awu121, https://...",# 613647 https://omim.org/entry/613647?search=...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,
17,D,symmetric,,globus pallida calcifications,,,ear of lynx,present,,,,present,,,,,,,,,SPG49,TECPR2,,,Complicated,AR,I,"<1 / 1,000,000",,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...",https://doi.org/10.1016/j.ajhg.2012.11.001,,https://www.orpha.net/consor/cgi-bin/Disease_S...,Now called HSAN9,
20,D,symmetric,,,probable microcephaly,,ear of lynx,present,present,,,"indenture, present",present,present,thinning post genu,,,,,,SPG54,DDHD2,"8:38,231,585-38,273,647",https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg...,Complicated,AR,"I, C","<1 / 1,000,000",GROWTH\nHeight\n- Short stature\nHEAD & NECK\n...,"10.3389/fneur.2018.01117 , https://www.ncbi.nl...",https://doi-org.proxy3.library.mcgill.ca/10.11...,# 615033 https://www.omim.org/entry/615033?sea...,https://www.orpha.net/consor/cgi-bin/Disease_S...,,

Would you like to search again?  no

Goodbye!